// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencyInjection

import (
	"Gel/src/gel/application/rules"
	"Gel/src/gel/application/services"
	"Gel/src/gel/persistence/repositories"
)

// Injectors from wire_injector.go:

// InitializeContainer wires all dependencies and returns a fully configured Container.
// The actual implementation is generated by Wire in wire_gen.go
func InitializeContainer() *Container {
	filesystemRepository := repositories.NewFilesystemRepository()
	gelRepository := repositories.NewGelRepository(filesystemRepository)
	initService := services.NewInitService(filesystemRepository)
	hashObjectService := services.NewHashObjectService(filesystemRepository, gelRepository)
	catFileService := services.NewCatFileService(filesystemRepository, gelRepository)
	updateIndexRules := rules.NewUpdateIndexRules(filesystemRepository)
	updateIndexService := services.NewUpdateIndexService(gelRepository, filesystemRepository, updateIndexRules)
	lsFilesService := services.NewLsFilesService(gelRepository, filesystemRepository)
	container := &Container{
		FilesystemRepository: filesystemRepository,
		GelRepository:        gelRepository,
		InitService:          initService,
		HashObjectService:    hashObjectService,
		CatFileService:       catFileService,
		UpdateIndexService:   updateIndexService,
		UpdateIndexRules:     updateIndexRules,
		LsFilesService:       lsFilesService,
	}
	return container
}
