// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencyInjection

import (
	"Gel/src/gel/application/services"
	"Gel/src/gel/core/helpers"
	"Gel/src/gel/persistence/repositories"
)

// Injectors from wire_injector.go:

// InitializeContainer wires all dependencies and returns a fully configured Container.
// The actual implementation is generated by Wire in wire_gen.go
func InitializeContainer() *Container {
	filesystemRepository := repositories.NewFilesystemRepository()
	gelRepository := repositories.NewGelRepository(filesystemRepository)
	zlibCompressionHelper := helpers.NewZlibCompressionHelper()
	initService := services.NewInitService(filesystemRepository)
	hashObjectService := services.NewHashObjectService(filesystemRepository, gelRepository, zlibCompressionHelper)
	catFileService := services.NewCatFileService(filesystemRepository, gelRepository, zlibCompressionHelper)
	container := &Container{
		FilesystemRepository: filesystemRepository,
		GelRepository:        gelRepository,
		CompressionHelper:    zlibCompressionHelper,
		InitService:          initService,
		HashObjectService:    hashObjectService,
		CatFileService:       catFileService,
	}
	return container
}
