//go:build wireinject
// +build wireinject

package dependencyInjection

import (
	"github.com/google/wire"
)

// InitializeContainer wires all dependencies and returns a fully configured Container.
// The actual implementation is generated by Wire in wire_gen.go
func InitializeContainer() *Container {
	wire.Build(
		RepositoryProviderSet,
		HelperProviderSet,
		ServiceProviderSet,
		wire.Struct(new(Container), "*"),
	)
	return nil // Wire will replace this with actual implementation
}
