// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencyInjection

import (
	"Gel/src/gel/application/rules"
	"Gel/src/gel/application/services"
	"Gel/src/gel/persistence/repositories"
)

// Injectors from wire_injector.go:

// InitializeContainer wires all dependencies and returns a fully configured Container.
// The actual implementation is generated by Wire in wire_gen.go
func InitializeContainer() *Container {
	filesystemRepository := repositories.NewFilesystemRepository()
	objectRepository := repositories.NewObjectRepository(filesystemRepository)
	indexRepository := repositories.NewIndexRepository(filesystemRepository)
	initService := services.NewInitService(filesystemRepository)
	hashObjectRules := rules.NewHashObjectRules(filesystemRepository)
	hashObjectService := services.NewHashObjectService(filesystemRepository, objectRepository, hashObjectRules)
	catFileService := services.NewCatFileService(filesystemRepository, objectRepository)
	updateIndexRules := rules.NewUpdateIndexRules(filesystemRepository)
	updateIndexService := services.NewUpdateIndexService(indexRepository, filesystemRepository, hashObjectService, updateIndexRules)
	lsFilesService := services.NewLsFilesService(indexRepository)
	container := &Container{
		FilesystemRepository: filesystemRepository,
		ObjectRepository:     objectRepository,
		IndexRepository:      indexRepository,
		InitService:          initService,
		HashObjectService:    hashObjectService,
		CatFileService:       catFileService,
		UpdateIndexService:   updateIndexService,
		LsFilesService:       lsFilesService,
		UpdateIndexRules:     updateIndexRules,
		HashObjectRules:      hashObjectRules,
	}
	return container
}
