// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencyInjection

import (
	rules2 "Gel/application/rules"
	services2 "Gel/application/services"
	repositories2 "Gel/persistence/repositories"
)

// Injectors from wire_injector.go:

// InitializeContainer wires all dependencies and returns a fully configured Container.
// The actual implementation is generated by Wire in wire_gen.go
func InitializeContainer() *Container {
	filesystemRepository := repositories2.NewFilesystemRepository()
	objectRepository := repositories2.NewObjectRepository(filesystemRepository)
	indexRepository := repositories2.NewIndexRepository(filesystemRepository)
	initService := services2.NewInitService(filesystemRepository)
	hashObjectRules := rules2.NewHashObjectRules(filesystemRepository)
	hashObjectService := services2.NewHashObjectService(filesystemRepository, objectRepository, hashObjectRules)
	catFileRules := rules2.NewCatFileRules(objectRepository)
	catFileService := services2.NewCatFileService(filesystemRepository, objectRepository, catFileRules)
	updateIndexRules := rules2.NewUpdateIndexRules(indexRepository)
	updateIndexService := services2.NewUpdateIndexService(indexRepository, filesystemRepository, objectRepository, hashObjectService, updateIndexRules)
	lsFilesService := services2.NewLsFilesService(indexRepository)
	addService := services2.NewAddService(updateIndexService)
	writeTreeService := services2.NewWriteTreeService(objectRepository, indexRepository)
	readTreeService := services2.NewReadTreeService(objectRepository, indexRepository)
	container := &Container{
		FilesystemRepository: filesystemRepository,
		ObjectRepository:     objectRepository,
		IndexRepository:      indexRepository,
		InitService:          initService,
		HashObjectService:    hashObjectService,
		CatFileService:       catFileService,
		UpdateIndexService:   updateIndexService,
		LsFilesService:       lsFilesService,
		AddService:           addService,
		WriteTreeService:     writeTreeService,
		ReadTreeService:      readTreeService,
		UpdateIndexRules:     updateIndexRules,
		HashObjectRules:      hashObjectRules,
	}
	return container
}
